### ISSUE TITLE
[Enhancement] Simplify Installation Processing

### ISSUE THREAD

**Issue by stevoleeto** [MCPCapital/harmonizeproject#2]
Expand potential user base by making things easier to install (i.e. no interaction needed with the CLI).

**Comment by 6by9** [comment]
Nifty project, congrats.

If you're looking to simplify things then:
- Assuming you're using Raspbian, then there's little point in using rpi-update. The kernel gets bumped fairly frequently anyway, and gets tested more heavily than rpi-update.
- I don't see any part of your code using v4l2-ctl or any other part of v4l-utils, therefore no point in building that, nor getting the relevant dependencies from apt. The version available as the v4l-utils package in Raspbian is recent enough for the majority of operations too.
- The ```bcm2835-v4l2``` kernel module is ONLY for the Pi camera. No USB device will use it as most will be UVC (USB Video Class) devices and use ```uvcvideo```. No amount of modprobing ```bcm2835-v4l2``` will change whether your USB device is detected. (Additionally,  since about the 4.19 kernel, bcm2835-v4l2 has been automatically loaded and attempts to detect the Pi camera as a platform device spawned from the VCHIQ driver).

I will suggest you are a little careful in your choice of capture device. I picked up a [device](https://www.ebay.co.uk/itm/USB-3-0-HDMI-Video-Capture-Card-HD-1080P-Grabber-Online-Class-Game-Recording/174299335403) that claimed to be USB3 and even has a blue USB3 plug, but in reality is only USB2. Thread on https://www.raspberrypi.org/forums/viewtopic.php?p=1696636#p1696636
```lsusb -t``` will tell you whether the device is really USB3.
```
pi@raspberrypi:~ $ lsusb -t
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 5000M
    |__ Port 1: Dev 2, If 0, Class=Mass Storage, Driver=usb-storage, 5000M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/4p, 480M
        |__ Port 2: Dev 3, If 0, Class=Video, Driver=uvcvideo, 480M <<<< This device. 480M means USB2 (5000M would be USB3)
        |__ Port 2: Dev 3, If 1, Class=Video, Driver=uvcvideo, 480M
        |__ Port 2: Dev 3, If 2, Class=Audio, Driver=snd-usb-audio, 480M
        |__ Port 2: Dev 3, If 3, Class=Audio, Driver=snd-usb-audio, 480M
        |__ Port 2: Dev 3, If 4, Class=Human Interface Device, Driver=usbhid, 480M
```
```v4l2-ctl --list-formats-ext``` will list out the formats that it supports. Mine ends up only doing MJPEG at full frame rate. Raw video (YUYV) maxes out at 10fps for 720p.
There are a fair number of these devices out, all based on the Macrosilicon chip (USB ID 534d:2109). It'd be interesting to know what your device reports.

Hope that helps.

**Comment by MCPCapital** [comment]
@6by9  I appreciate the time and effort you've put into this well-detailed write up. 

I haven't set this up from scratch in a while and I remember encountering issues with the video input, so that must be why I thought running rpi-update and installing v4l2 was necessary.  We also used MJPEG as that seems to be the most efficient format for maintaining framerate! Just to confirm - v4l2 wouldn't be necessary for _any_ usb capture device?

My stuff is currently in storage b/c COVID. I'll get my hands on these items again later this week. When I do, I'll run lsusb on my capture device and share the output; as well as try installing this from scratch to more thoroughly define the dependencies. You are clearly well-versed on this topic and I trust your analysis so I'll update the readme to remove that dependency now. Thanks again very much for your input!!

Finally - I think the acceptance criteria for this issue would be to have an install script where the user could clone this git, cd in, and run `sudo ./setup.sh` - Should be able to complete this this week.

**Comment by MCPCapital** [comment]
I have confirmed v4l2 is not needed. Thank you for this important clarification! I have created a setup script for easy installation of dependencies.

I will now close this issue, feel free to re-open if you have any further comments. Thank you again for your input!
